FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore src/AttendanceService/AttendanceService/AttendanceService.csproj

RUN dotnet publish src/AttendanceService/AttendanceService/AttendanceService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "AttendanceService.dll"]